### PR TITLE
integration-test: Use veth pair instead of lo

### LINKED ISSUE #422: integration-tests: Don't use lo interface for XDP, create some veths instead
Currently, integration tests are attaching XDP programs to `lo` inteface:

https://github.com/aya-rs/aya/blob/f3262e87bd6ff895537df47fcf5d17c598e564cc/test/integration-test/src/tests/load.rs#L24

That's not a good approach, it's too intrusive, especially if the test fails or if for some reason the XDP program doesn't get unloaded. `lo`, as well as any already existing NICs, shouldn't be touched.

To test XDP, we should rather create some new, fake veth interfaces, which then we remove after running a test. Such interfaces should be also safe to remove manually if anything goes wrong with cleaning up after the test.

### PR DESCRIPTION
**Pull request by kevinji**
Fixes #422. I split the initial codegen commit out to #919 to clean this PR up.

I would like some help debugging the last 4 test failures:
```
---- tests::smoke::list_loaded_maps stdout ----
Entered network namespace aya-test-404672-4
thread 'tests::smoke::list_loaded_maps' panicked at test/integration-test/src/tests/smoke.rs:117:23:
called `Result::unwrap()` on an `Err` value: LoadError { io_error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, verifier_log:  }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exited network namespace aya-test-404672-4

---- tests::smoke::list_loaded_programs stdout ----
Entered network namespace aya-test-404672-5
thread 'tests::smoke::list_loaded_programs' panicked at test/integration-test/src/tests/smoke.rs:84:23:
called `Result::unwrap()` on an `Err` value: LoadError { io_error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, verifier_log:  }
Exited network namespace aya-test-404672-5

---- tests::xdp::af_xdp stdout ----
Entered network namespace aya-test-404672-6
thread 'tests::xdp::af_xdp' panicked at test/integration-test/src/tests/xdp.rs:57:22:
called `Result::unwrap()` on an `Err` value: Errno(19: No such device)
Exited network namespace aya-test-404672-6

---- tests::xdp::cpumap_chain stdout ----
Entered network namespace aya-test-404672-7
thread 'tests::xdp::cpumap_chain' panicked at test/integration-test/src/tests/xdp.rs:182:5:
assertion `left == right` failed
  left: 0
 right: 1
Exited network namespace aya-test-404672-7
```

I'm not sure if introducing the network namespace caused behavior to now be different.

### CODE REVIEW

**Comment by astoycos** [comment]
Additionally you consider using dummy interfaces here rather than veth pairs? (as mentioned in #422) ?

**Comment by kevinji** [comment]
@astoycos I saw a comment in #561 suggesting veth pairs instead of dummies so that's why I went with this approach. I'll look into why the macOS VM tests are failing.

**Comment by astoycos** [comment]
Ack just read that, sounds good thanks!

**Comment by kevinji** [comment]
@astoycos I'm having trouble debugging the exact issue as I'm unable to get the QEMU setup working locally, so have been (slowly) trying to debug while pushing changes to CI.

My current hypothesis is that since the integration tests run as the `/init` process on `initramfs`, perhaps some veth module is not yet loaded which causes creation to fail. I ran the equivalent `ip link` command to try to create a veth and ran into similar issues. It's also possible that veth creation relies on something on the filesystem that it can't access for some reason during the `/init` script.

**Pull request closed without merging**
