### PR TITLE
bpf: Add bpf_d_path helper

### PR DESCRIPTION
**Pull request by vadorovsky**
Add a helper which writes a full path of the given `path` kernel object
to the buffer. Useful for resolving paths when using `file` or `ìnode`
objects.

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

### CODE REVIEW

**Comment by shaneutt** [comment]
So as I understand it, we have a helper function here that we could merge and we feel would provide some value, _but_ we did have some further changes we wanted to make. Is it a case where we can create a follow-up issue for the additional changes, and link it in the function documentation so that we can merge this as-is and make improvements in later iterations? Or is it a case where we really should finish those changes as a part of this PR?

**Comment by vadorovsky** [comment]
I don't think we need any more changes. I already did everything we discussed on discord (returning byte slice and documenting `core::str::from_utf8_unchecked`). It just needs to be reviewed by @alessandrod or @dave-tucker.

**Comment by vadorovsky** [comment]
@alessandrod ping, it's a tiny one

**Comment by vadorovsky** [comment]
@alessandrod PTAL

**Comment by vadorovsky** [comment]
this helper is discouraged to use nowadays, let's close it

**Pull request closed without merging**
