### PR TITLE
ci: cache downloads

### PR DESCRIPTION
**Pull request by tamird**
See commit message.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aya-rs/aya/1114)

### CODE REVIEW

**Comment by vadorovsky** [comment]
Superseded by #1115, right?

**Comment by tamird** [comment]
Nah, this is still good to do. I'll rebase it in a bit.

**Comment by tamird** [comment]
Yep, we're gonna need this one too (once https://github.com/oxidecomputer/third-party-api-clients/issues/96 is addressed).

I just caught a 
```
Error: failed to download gen_init_cpio.c

Caused by:
    Rate limited for the next 1144 seconds
```
over in #1115.

**Comment by tamird** [comment]
Also this is so strange. See https://github.com/orgs/community/discussions/146957.

**Comment by tamird** [comment]
@vadorovsky can you TAL?

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
