### PR TITLE
PerfEvent: add option to set the inherit bit

### PR DESCRIPTION
**Pull request by akhramov**
The inherit bit allows extending perf scope to the new child processes.

(I am not sure about the API, though)

### CODE REVIEW

**Comment by alessandrod** [comment]
Thanks for the PR!

> (I am not sure about the API, though)

What does libbpf do? I'm inclined to say we should set inherit=1 by default?

**Comment by akhramov** [comment]
> What does libbpf do

https://github.com/torvalds/linux/blob/82714078aee4ccbd6ee7579d5a21f8a72155d0fb/tools/lib/bpf/libbpf.c#L12441-L12448

It doesn't set the bit either.

>  I'm inclined to say we should set inherit=1 by default?

We can, but it can ruin it for users who don't expect events from the sub-processes.

**Comment by alessandrod** [comment]
I see.

I think inherit applies to all variants tho right? So maybe it should be an extra bool argument to attach()?

**Comment by alessandrod** [comment]
Ping? 😊

**Comment by akhramov** [comment]
Hey, sorry for the delay. I found my way around this, so probably we should close the PR.

**Pull request closed without merging**
