### PR TITLE
integration-test: Remove integration-test-macros

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/aya-rs/aya/640)

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
LGTM

**Review by ajwerner — COMMENTED** [review]
nice

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/640#-:-NZlvzQ8EQYw2c40puc8:bb7lbs2)* status: all files reviewed, 1 unresolved discussion (waiting on @alessandrod and @tamird)

___
*[`test/README.md` line 49 at r3](https://reviewable.io/reviews/aya-rs/aya/640#-NZlvLZA2WDjYhDF1esJ:-NZlvLZB3NmxHUvgrHI8:b-68t3dw) ([raw file](https://github.com/aya-rs/aya/blob/b3231ed20095eebe6fada5467c9b3e85b276cb83/test/README.md#L49)):*
> ```Markdown
> - C eBPF code should live in `integration-test/src/bpf/${NAME}.bpf.c`. It's automatically compiled and made available as `${OUT_DIR}/${NAME}.bpf.o`.
> - Any bytecode should be included in the integration test binary using `include_bytes_aligned!`.
> - Tests should be added to `integration-test/src/test`.
> ```

Does this imply unit tests should not be added to the other crates? Maybe this whole section should say something about integration tests or end-to-end tests?

**Review by tamird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/640)* status: 8 of 20 files reviewed, all discussions resolved (waiting on @ajwerner and @alessandrod)

___
*[`test/README.md` line 49 at r3](https://reviewable.io/reviews/aya-rs/aya/640#-NZlvLZA2WDjYhDF1esJ:-NZm6GNNDYaFPYLKjpJW:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/b3231ed20095eebe6fada5467c9b3e85b276cb83/test/README.md#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does this imply unit tests should not be added to the other crates? Maybe this whole section should say something about integration tests or end-to-end tests?
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 12 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/640)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @alessandrod)

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/640)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @alessandrod)

**Review by alessandrod — APPROVED** [review]

**Pull request merged**
