### PR TITLE
aya: Truncate long program names

### PR DESCRIPTION
**Pull request by dave-tucker**
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

### CODE REVIEW

**Comment by dave-tucker** [comment]
@alessandrod this is a quick fix :laughing: I know you had bigger plans for better name truncation.

**Comment by alessandrod** [comment]
What happens if two programs have the same 16 byte prefix? Is that a hard failure? If so I'm tempted to switch off this whole prog_name business until we have a plan 😅

**Comment by dave-tucker** [comment]
I don't think names need to be unique. Let me check :)

**Comment by dave-tucker** [comment]
```
194: xdp  name foo2  tag 3b185187f1855c4c  gpl
        loaded_at 2022-01-16T11:32:17+0000  uid 0
        xlated 16B  jited 18B  memlock 4096B
        btf_id 416
        pids foo2(272669)
200: xdp  name foo2  tag 3b185187f1855c4c  gpl
        loaded_at 2022-01-16T11:32:34+0000  uid 0
        xlated 16B  jited 18B  memlock 4096B
        btf_id 434
        pids foo2(272974)
 ```

**Pull request merged**
