### PR TITLE
Appease clippy

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/aya-rs/aya/1122)

### CODE REVIEW

**Comment by tamird** [comment]
Merged without review? Let's not do that, please. Even the title has a typo.

**Comment by vadorovsky** [comment]
Fine, I will ping for review next time. That said, there were many other "Appease clippy" PRs which were merged without review as well.

**Comment by tamird** [comment]
Reviewed:
https://github.com/aya-rs/aya/pull/1046
https://github.com/aya-rs/aya/pull/1040
https://github.com/aya-rs/aya/pull/1016
https://github.com/aya-rs/aya/pull/969
https://github.com/aya-rs/aya/pull/952
https://github.com/aya-rs/aya/pull/933

Not reviewed:
https://github.com/aya-rs/aya/pull/922 (merged 16 hours after last update)
https://github.com/aya-rs/aya/pull/911 (merged right away)

You're right that there's some precedent, but in the majority of cases, I wait for review.

**Comment by vadorovsky** [comment]
Alright, sorry again. I will make sure to always ping you.

**Pull request merged**
